name       : python-pyside2-tools
version    : 5.15.3
release    : 3
source     :
    - https://download.qt.io/official_releases/QtForPython/pyside2/PySide2-5.15.3-src/pyside-setup-opensource-src-5.15.3.tar.xz : 7ff5f1cc4291fffb6d5a3098b3090abe4d415da2adec740b4e901893d95d7137
license    :
    - GPL-2.0-or-later
    - LGPL-3.0-or-later
component  : programming.python
summary    : Python bindings for the Qt cross-platform application and UI framework
description: |
    PySide2 is the official Python module from the Qt for Python project, which provides access to the complete Qt5 framework
clang      : yes
builddeps  :
    - pkgconfig(Qt5Core)
    - pkgconfig(pyside2)
    - pkgconfig(shiboken2)
setup      : |
    cd sources/pyside2-tools
    %cmake_ninja -DBUILD_SHARED_LIBS=ON -DBUILD_TESTS=OFF -DPYTHON_EXECUTABLE=/usr/bin/python3
build      : |
    cd sources/pyside2-tools
    %ninja_build
install    : |
    cd sources/pyside2-tools
    %ninja_install
    rm -f $installdir/usr/bin/{rcc,uic}
    install -Dm00755 $pkgfiles/pyside2-rcc $installdir/usr/bin/pyside2-rcc
    install -Dm00755 $pkgfiles/pyside2-uic $installdir/usr/bin/pyside2-uic
